core/urls.py
from core import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.HomepageView.as_view(),name='home'),
    path('login/',views.LoginRegisterView.as_view(),name='login'),
    path('create/',views.AdminAddPostView.as_view(),name='create_post'),
    path('edit/<int:pk>',views.AdminEditPostView.as_view(),name='edit_post'),
    path('dashboard/',views.AdminDashboardView.as_view(),name='dashboard'),
    path('all_posts/',views.AdminAllPosts.as_view(),name='all_posts'),
    path('user/<int:pk>/',views.AdminEditUserView.as_view(),name='edit_user'),
    path('logout/',views.logout_user,name='logout'),
    path('not_verified/',views.RedirectPage.as_view(),name='not_verified'),
    path('contents/<int:pk>/',views.PostDetail.as_view(),name='post_detail'),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

faj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]

core/models.py
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField

class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Post(models.Model):
    title = models.CharField(max_length=100,null=True)
    content = RichTextField()
    image = models.ImageField(null=True,blank=True)
    video_link = models.CharField(max_length=250,blank=True,null=True)

    def __str__(self):
        return self.title

core/forms.py
from pyexpat import model
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post, Profile

class CreatePostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    content = forms.CharField(widget=CKEditorWidget())
    image = forms.ImageField(required=False,widget=forms.ClearableFileInput(attrs={'class':'form-control'}))
    video_link = title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Post
        fields = ['title','content','image','video_link']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('verified',)

core/views.py
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin


from core.models import Post,Profile
from core.forms import CreatePostForm,ProfileForm
from core.mixins import CheckVerificationMixin, StaffAccessMixin


class RedirectPage(LoginRequiredMixin,generic.ListView):
    template_name = 'core/redirect_page.html'
    model = Post

class PostDetail(LoginRequiredMixin,CheckVerificationMixin,generic.DetailView):
    template_name = 'core/content_details.html'
    model = Post
    context_object_name = 'post'

class LoginRegisterView(generic.View):
    templage_name = 'core/login.html'
    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/')
        return render(request,self.templage_name)

    def post(self,request,*args,**kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        form_type = request.POST.get('form_type')
        if form_type == 'login':
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                if user.is_staff:
                    return HttpResponseRedirect(reverse('dashboard'))
                return HttpResponseRedirect(reverse('home'))
            else:
                return render(request,self.templage_name,{'error':'Login credential do not exist'})
        else:
            user = User.objects.create_user(username=username,password=password,email=email)
            user.save()
            profile = Profile.objects.create(user=user)
            profile.save()
            login(request,user)
            return HttpResponseRedirect('/')
        # return self.get(request,*args,**kwargs)

class HomepageView(LoginRequiredMixin,CheckVerificationMixin,generic.ListView):
    template_name = 'core/index.html'
    # template_name = 'core/cards.html'
    redirect_url = reverse_lazy('not_verified')
    model = Post
    context_object_name = 'posts'


class AdminDashboardView(LoginRequiredMixin,StaffAccessMixin,generic.ListView):
    template_name = 'core/dashboard.html'
    redirect_url = reverse_lazy('home')
    model = Profile
    context_object_name = 'audience'


class AdminAllPosts(LoginRequiredMixin,StaffAccessMixin,generic.ListView):
    model = Post
    template_name = 'core/all_posts.html'
    context_object_name = 'posts'
     


class AdminEditUserView(LoginRequiredMixin,StaffAccessMixin,generic.View):
    template_name = 'core/edit_user.html'
    redirect_url = reverse_lazy('home')
    def get(self,request,*args,**kwargs):
        user = get_object_or_404(User,pk=kwargs['pk'])
        profile = get_object_or_404(Profile,user=user)
        form = ProfileForm(instance=profile)
        return render(request,self.template_name,{'form':form,'user':user})

    def post(self,request,*args,**kwargs):
        
        user = get_object_or_404(User,pk=kwargs['pk'])
        profile = get_object_or_404(Profile,user=user)
        form = ProfileForm(request.POST,instance=profile)
        if form.is_valid():
            form.user = user
            print(form.user.id)
            form.save()
            return HttpResponseRedirect(reverse('dashboard'))
        return self.get(request,*args,**kwargs,form=form)

class AdminAddPostView(LoginRequiredMixin,StaffAccessMixin,generic.View):
    template_name = 'core/create_post.html'
    redirect_url = reverse_lazy('home')
    def get(self,request,*args,**kwargs):
        form = CreatePostForm()
        context = {'form':form}
        return render(request,self.template_name,context)

    def post(self,request,*args,**kwargs):
        form = CreatePostForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home'))
        context = {'form':form}
        return render(request,self.template_name,context)


class AdminEditPostView(LoginRequiredMixin,StaffAccessMixin,generic.View):
    template_name = 'core/create_post.html'
    redirect_url = reverse_lazy('home')

    def get(self,request,*args,**kwargs):
        query = get_object_or_404(Post,pk=kwargs['pk'])
        form = CreatePostForm(instance=query)
        context = {'form':form}
        return render(request,self.template_name,context)

    def post(self,request,*args,**kwargs):
        query = get_object_or_404(Post,pk=kwargs['pk'])
        form = CreatePostForm(request.POST,instance=query)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home'))
        context = {'form':form}
        return render(request,self.template_name,context)

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

core/templates/core/all_posts.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-2 mb-3" style="padding: 20px;">
    <div class="row g-2">
        {% for post in posts %}
        <div class="col-md-3">
            <div class="solution_cards_box">
            <div class="solution_card h-100">
              <div class="hover_color_bubble"></div>
              <div class="so_top_icon">
                <svg id="Layer_1" enable-background="new 0 0 512 512" height="50" viewBox="0 0 512 512" width="40" xmlns="http://www.w3.org/2000/svg">
                  <g>
                    <g>
                      <g>
                        <g>
                          <path d="m47.478 452.317 295.441 19.76c5.511.369 10.277-3.8 10.645-9.31l28.393-424.517c.369-5.511-3.8-10.276-9.31-10.645l-295.441-19.76c-5.511-.369-10.276 3.8-10.645 9.31l-28.394 424.517c-.368 5.511 3.8 10.277 9.311 10.645z" fill="#fae19e" />
                        </g>
                        <g>
                          <g>
                            <g>
                              <g>
                                <g>
                                  <path d="m17.5 504.177h226.14l79.96-79.605v-355.86c0-5.523-4.477-10-10-10h-296.1c-5.523 0-10 4.477-10 10v425.466c0 5.522 4.477 9.999 10 9.999z" fill="#fff9e9" />
                                </g>
                                <path d="m313.601 58.712h-40c5.523 0 10 4.477 10 10v355.861l-.258 40.078 40.258-40.078v-355.861c0-5.523-4.477-10-10-10z" fill="#fff4d6" />
                              </g>
                            </g>
                          </g>
                          <path d="m243.64 504.177v-70.253c0-5.523 4.477-10 10-10h69.96z" fill="#ffeec2" />
                        </g>
                      </g>
                      <g>
                        <path d="m468.636 248.58-33.372.165v-50.826c0-9.183 7.463-16.662 16.673-16.708h.007c9.217-.046 16.693 7.371 16.693 16.562v50.807z" fill="#fed23a" />
                        <path d="m451.96 504.177c-10.362-10.277-16.196-24.263-16.208-38.857l-.062-73.973c0-.644.524-1.169 1.171-1.173l30.038-.149c.647-.003 1.171.517 1.171 1.161l.062 74.079c.012 14.531-5.749 28.472-16.015 38.756z" fill="#54b1ff" />
                        <path d="m451.959 469.333h-.01c-14.434.072-26.14-11.542-26.14-25.935v-213.527c0-6.778 5.477-12.283 12.255-12.316l27.626-.137c6.826-.034 12.378 5.49 12.378 12.316v213.436c0 14.38-11.687 26.091-26.109 26.163z" fill="#fdf385" />
                        <path d="m465.69 217.417-23.769.118c6.037.79 10.708 5.94 10.708 12.198v213.437c0 9.823-5.455 18.397-13.507 22.87 3.79 2.115 8.164 3.317 12.826 3.293h.01c14.422-.072 26.109-11.783 26.109-26.163v-213.436c.001-6.826-5.551-12.351-12.377-12.317z" fill="#faee6e" />
                        <path d="m491.274 247.925-71.615.355c-7.305.036-13.226 5.968-13.226 13.248 0 7.281 5.921 13.153 13.226 13.117l58.389-.29v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c0-7.28-5.922-13.152-13.226-13.116z" fill="#54b1ff" />
                        <g>
                          <path d="m491.274 247.925-38.441.188-.167 26.311 25.381-.067v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c.001-7.282-5.921-13.154-13.225-13.118z" fill="#3da7ff" />
                        </g>
                      </g>
                    </g>
                    <g fill="#060606">
                      <path d="m373.147 20.122-295.44-19.761c-9.631-.638-17.984 6.665-18.629 16.293l-2.311 34.557h-39.267c-9.649 0-17.5 7.851-17.5 17.5v425.466c0 9.649 7.851 17.5 17.5 17.5h226.141c1.96 0 3.902-.801 5.292-2.185l34.138-33.987c.347.074.701.133 1.065.157l58.282 3.898c9.302.614 18.005-6.952 18.629-16.293l28.393-424.515c.639-9.528-6.766-17.993-16.293-18.63zm-122.006 465.902v-52.1c0-1.378 1.122-2.5 2.5-2.5h51.9zm94.939-23.757c-.244 1.51-1.131 2.286-2.66 2.327l-46.28-3.096 31.752-31.611c1.414-1.407 2.209-3.32 2.209-5.315v-355.86c0-9.649-7.851-17.5-17.5-17.5h-77.993c-9.697 0-9.697 15 0 15h77.993c1.379 0 2.5 1.122 2.5 2.5v347.712h-62.46c-9.649 0-17.5 7.851-17.5 17.5v62.753h-218.641c-1.378 0-2.5-1.122-2.5-2.5v-425.465c0-1.378 1.122-2.5 2.5-2.5h178.168c9.697 0 9.697-15 0-15h-123.868l2.244-33.556c.244-1.511 1.131-2.286 2.661-2.327l295.44 19.76c1.511.244 2.287 1.131 2.328 2.661z" />
                      <path d="m267.827 237.047h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z" />
                      <path d="m267.827 289.332h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z" />
                      <path d="m55.774 192.262c0 4.142 3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5h-204.553c-4.142 0-7.5 3.358-7.5 7.5z" />
                      <path d="m91.807 139.977c0 4.142 3.358 7.5 7.5 7.5h132.487c4.142 0 7.5-3.358 7.5-7.5s-3.358-7.5-7.5-7.5h-132.487c-4.142 0-7.5 3.358-7.5 7.5z" />
                      <path d="m194.755 438.787c-13.489.036-26.978.065-40.467.086-4.534.007-9.067.013-13.6.016-8.215.006-13.75-1.643-15.59-10.679-1.556-7.64-12.364-6.613-14.464 0-5.19 16.337-13.774 9.936-18.582-1.053-4.797-10.963-6.027-23.233-8.122-34.9-1.54-8.573-14.506-6.17-14.732 1.994-.298 10.751-1.302 21.331-4.031 31.758-2.815 10.758-7.034 21.097-11.222 31.376-3.651 8.961 10.867 12.816 14.464 3.988 3.711-9.108 7.427-18.266 10.193-27.714 5.14 12.36 15.774 26.34 30.927 18.101 2.819-1.533 5.452-3.712 7.763-6.253 7.88 9.106 19.609 8.388 30.584 8.375 15.627-.02 31.254-.054 46.881-.095 9.649-.025 9.667-15.025-.002-15z" />
                      <path d="m505.932 246.439c-3.897-3.878-9.255-5.867-14.695-6.014l-5.668.028v-10.719c0-6.529-3.878-13.427-9.433-16.862v-15.098c0-31.069-48.372-30.934-48.372.146v15.1c-5.659 3.498-9.455 9.741-9.455 16.852v10.982c-24.966 1.7-25.037 39.745.028 41.232.16 33.575.152 66.6-.028 100.737-.049 9.414 14.949 9.966 15 .079.18-34.166.188-67.22.029-100.823l37.211-.185s-.048 110.848-.048 160.784c0 24.338-37.219 24.5-37.219-.253l.013-13.677c.585-9.68-14.387-10.583-14.973-.904v12.834c0 11 3.402 20.316 9.988 26.869.586 15.693 7.198 30.878 18.369 41.956 3.205 3.18 7.642 2.208 10.744-.182 11.365-11.385 17.769-26.394 18.169-42.414 4.951-4.931 9.908-9.896 9.908-26.896l.006-68.351c12.97 3.689 26.494-6.348 26.494-19.946v-90.672c0-5.523-2.155-10.709-6.068-14.603zm-72.623-5.727v-10.841c0-2.219 1.523-4.08 3.573-4.633l30.025-.149c.84.208 1.615.605 2.243 1.231.915.911 1.419 2.123 1.419 3.414v10.794zm18.671-52c4.604 0 9.155 4.514 9.155 9.062v12.166l-18.372.091v-12.111c.001-5.053 4.133-9.183 9.217-9.208zm-.011 303.901c-3.487-4.942-6.009-10.531-7.417-16.406 2.322.503 4.674.765 7.027.765 2.627 0 5.253-.326 7.839-.957-1.374 5.964-3.892 11.587-7.449 16.598zm45.031-140.899c0 7.101-11.452 7.66-11.452.131 0 0 .013-70.974.021-77.48.005-4.196-3.483-7.509-7.558-7.509l-58.389.29c-7.242 0-7.073-11.331.074-11.366l71.615-.355c3.463.295 5.359 2.168 5.688 5.617v90.672z" />
                    </g>
                  </g>
                </svg>
              </div>
              <div class="solu_title">
                <h3>{{ post.title }}</h3>
              </div>
              <div class="solu_description">
                <p>
                  {{ post.content|safe|truncatewords:10 }}
                </p>
                <a href="{% url 'post_detail' post.pk %}">
                <button type="button" class="read_more_btn">Content Detail</button>
                </a>
              </div>
            </div>
          </div>
        </div>
        
        {% endfor %}
    </div>
    <div class="addpost">
        <a href="{% url 'create_post' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-file-earmark-plus-fill" viewBox="0 0 16 16">
              <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM8.5 7v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 1 0z"/>
            </svg>
        </a>
    </div>
</div>

{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/cards.css' %}">
    <script src="{% static 'core/js/bootstrap.bundle.js' %}"></script>

    <title>FAJ | Accounting</title>
</head>
<body>
    
</svg>
    {% include 'core/navbar.html' %}
    {% block content %}

    {% endblock %}

    {% block extra_script %}

    {% endblock %}
</body>
</html>

core/templates/core/content_details.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container" id="content">
    <h2>{{ post.title }}</h2>
    {% if post.video_link %}
    <iframe id="frame" width="400" height="250"
            src="{{ post.video_link }}">
    </iframe>
    {% endif %}
    {{ post.content|safe }}
</div>
<div class="bottom mt-3">
    <p>{% if request.user.is_staff %}<a href="{% url 'dashboard' %}">Back to Home</a> | <a href="{% url 'edit_post' post.pk %}">Edit Post</a>{% else %} <a href="/">Back to Home</a> |{% endif %}</p>
</div>
{% endblock %}

core/templates/core/create_post.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-2 mb-3 pt-2 pb-2">
    <div class="col-md-8 offset-md-1">
        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            <div class="mb-3">
              <label for="id_title" class="form-label">Post Title</label>
              {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="id_content" class="form-label">Body Content</label>
            {{ form.content }}    
            </div>
            
            <div class="mb-3">
                <label for="id_image" class="form-label">Select Image</label>
                {{ form.image }}
            </div>
            
            <div class="mb-3">
                <label for="id_video_link" class="form-label">Video Link</label>
                {{ form.video_link }}
            </div>

            <div class="mb-3">
                <input class="btn btn-danger block" style="background: linear-gradient(140deg,#42c3ca 0%,#42c3ca 50%,#42c3cac7 75%) !important;border: none;" type="submit" value="Create">
            </div>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/dashboard.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-2">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Verification Status</th>
            </tr>
        </thead>
        <tbody>
            {% for profile in audience %}
            <tr>
                <td>{{ profile.user.username }}</td>
                <td>{{ profile.user.email }}</td>
                <td>{{ profile.verified }}</td>
                <td><a href="{% url 'edit_user' profile.user.id %}">Edit</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

core/templates/core/edit_user.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <div id="rrs">
        <!-- <div class=""> -->
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <input class="btn btn-danger block mt-3" style="background: linear-gradient(
    140deg,#42c3ca 0%,#42c3ca 50%,#42c3cac7 75%) !important;border: none;" type="submit" value="Save">
            </form>
        <!-- </div> -->
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
<div id="rrs">
    <div id="login">
        
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_username">Username</label>
                <input class="form-control" type="text" name="username" id="id_username">
            </div>
            <div class="mb-3">
                <label for="id_password">Password</label>
                <input class="form-control" type="password" name="password" id="id_password">
            </div>

            <input type="hidden" name="form_type" value="login">
            <input class="btn btn-success block" style="background: linear-gradient(
    140deg,#42c3ca 0%,#42c3ca 50%,#42c3cac7 75%) !important;border: none;" type="submit" value="Login">
        </form>
        <span>Wanna join Us? </span><span id="reg" style="font-weight: bold;" role="button">Register</span>
    </div>

    <div id="register" style="display: none;">
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_username">Username</label>
                <input class="form-control" type="text" name="username" id="id_username">
            </div>
            <div class="mb-3">
                <label for="id_email">Email</label>
                <input class="form-control" type="email" name="email" id="id_email">
            </div>
            <div class="mb-3">
                <label for="id_password">Password</label>
                <input class="form-control" type="password" name="password" id="id_password">
            </div>
            <input type="hidden" name="form_type" value="register">
            <input class="btn block" style="background: linear-gradient(
    140deg,#42c3ca 0%,#42c3ca 50%,#42c3cac7 75%) !important;border: none;" type="submit" value="Register">
        </form>
        <span>Already a User? </span><span id="log" style="font-weight: bold;" role="button">Login</span>
    </div>
</div>
{% endblock %}

{% block extra_script %} 
<script>
loginForm = document.getElementById('login');
registerForm = document.getElementById('register');

function showLogin() {
    loginForm.style.display = 'block';
    registerForm.style.display = 'none';
}

function showRegister() {
    loginForm.style.display = 'none';
    registerForm.style.display = 'block';
}

document.getElementById('log').addEventListener('click',showLogin)
document.getElementById('reg').addEventListener('click',showRegister)

</script>
{% endblock %}

core/templates/core/navbar.html
{% if request.user.is_staff %}

<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="background: linear-gradient(
    140deg,#42c3ca 0%,#42c3ca 50%,#42c3cac7 75%) !important;">
  <div class="container-fluid">
    <a class="navbar-brand" style="color: #f1f1f1;font-weight: bold;" href="{% url 'dashboard' %}">FAJ ACCOUNTANCY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex">
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bolder; text-decoration: underline; text-underline-offset: 5px;" >Admin Section</a>
        </li>
      
      </ul>
    </div>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'all_posts' %}">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Others</a>
        </li>
      </ul>
    </div>
    
  </div>
</nav>

{% else %}
<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="background: linear-gradient(
    140deg,#42c3ca 0%,#42c3ca 50%,#42c3cac7 75%) !important;">
  <div class="container-fluid">
    <a class="navbar-brand" style="color: #f1f1f1;font-weight: bold;" href="/">FAJ ACCOUNTANCY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link">{{ request.user.username }}</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% endif %}

core/templates/core/redirect_page.html
{% extends 'core/base.html' %}

{% block content %}
<div id="rrs">
<h3>You currently do not have access to view contents on this site</h3>
<h4>Kindly meet admin to gain acces to the amazing contents of this site. <br> click here to message admin</h4>
</div>
{% endblock %}